### PR TITLE
Add daniel

### PR DESCRIPTION
**Pull request by rymaju**
## Why
To add Daniel to the site.

### CODE REVIEW

**Review by atulyamiglani — APPROVED** [review]
Looks good 👍

**Review by aiyan — APPROVED** [review]
✨

**Review by djung335 — APPROVED** [review]
very cool

**Review by connernilsen — CHANGES_REQUESTED** [review]
I hate this it looks terrible 🤣

**Comment by rymaju** [comment]
@connernilsen :angery:

**Comment by connernilsen** [comment]
P.S. just kidding! I'm leaving the blocking review so that nobody accidentally merges it in. I'll come back in a couple of days and clear it

**Review by yanDavid21 — APPROVED** [review]
LGTM!

**Review by connernilsen — APPROVED** [review]
O P E N
S E S A M E

**Pull request merged**
